### ISSUE TITLE
Contradiction in documentation and license

### ISSUE THREAD

**Issue by GabLeRoux** [OndrejNepozitek/ProceduralLevelGenerator-Unity#29]
Hey there, just found your project and it's cool. You got some nice docs too, good job, that is some great work. :)

I just wanted to let you know there is a contradiction in your ReadMe and the actual license being used to serve the code.

> Terms of use
> The plugin can be used in bot commercial and non-commerical projects but cannot be redistributed or reselled. If you want to include this plugin in your own asset, please contact me and we will figure that out.

But you're using an [MIT License](https://github.com/OndrejNepozitek/ProceduralLevelGenerator-Unity/blob/master/LICENSE) which explicitly states that it gives the _[...] rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software [...]_.

![image](https://user-images.githubusercontent.com/1264761/62915211-83aad880-bd61-11e9-94b1-a08a6521bc4d.png)

I'm not a lawyer so I'm not sure at all, but I think the license has priority here. Anyway, I just wanted you to know. I don't think this can be solved for current project (or at least current revision) since the license is already part of the code. There may be more appropriate licenses out there if you don't want people to _distribute_. Some people also use the concept of double license so anyone can use the code if they grab the project from source, but they may have to pay to use a prebuilt library, etc.

Again, since I'm not a lawyer, maybe I'm totally wrong and having a `Terms of use` in the documentation may have priority, but that's probably just confusing.

Feel free to close this issue and have an awesome day ;)

**Comment by OndrejNepozitek** [comment]
Hey! Thanks for pointing this out.

I know that the license and documentation are in a contradiction but I just wanted to show that I wouldn't be happy if someone started reselling the library. However, as I'm not a lawyer, it seemed to me to be too complicated to come up with some complex licensing so I decided to just write that in the Terms of use and deal with that properly only if it ever becomes a problem.
