### ISSUE TITLE
eature `interpolated strings' cannot be used because it is not part of the C# 4.0 language specification

### ISSUE THREAD

**Issue by Sven65** [OndrejNepozitek/ProceduralLevelGenerator-Unity#30]
Imported the unity package into Unity 2018.1.2.f1 and got the error `Assets/ProceduralLevelGenerator/Scripts/GeneratorPipeline/DungeonGenerators/GraphBasedGenerator/GraphBasedGeneratorTask.cs(71,16): error CS1644: Feature `interpolated strings' cannot be used because it is not part of the C# 4.0 language specification`

The error also appears in other files.

**Comment by OndrejNepozitek** [comment]
Hey! 
Please make sure that you have Scripting runtime version in Unity set to .NET 4.X equivalent or .NET Standard 2.0.
