### ISSUE TITLE
can not add prefab to collidable tilemap

### ISSUE THREAD

**Issue by muafakul** [OndrejNepozitek/ProceduralLevelGenerator-Unity#31]
just it , or i still dont understand

**Comment by OndrejNepozitek** [comment]
Hey, can you please provide some details of your problem?

**Comment by muafakul** [comment]
im trying to add spike game object to the tilemap named collidable ,,,,,,,,,,,but when i generate the map ,, that spike wont appear

**Comment by OndrejNepozitek** [comment]
Tilemaps are meant only for tiles. But you want to spawn a GameObject, right?

Not long ago, someone asked me how to include a GameObject prefab in a room template and then spawn it inside the room after the map is generated. Is that what you need?

**Comment by muafakul** [comment]
i think i can use brush tile or what is that called ,,,,,,,,,,,,,

**Comment by muafakul** [comment]
someting like game object tile ,, so , i dont use default brush but gameobject brush

**Comment by muafakul** [comment]
and i want to ask other things ,, how to remove auto add rigi body and composite colider ? imean when i generate , i dont want to add rigibody and composite clider

**Comment by OndrejNepozitek** [comment]
You can implement your own TilemapLayersHandler (as a ScriptableObject) and assign it to the PayloadInitilaizer in the DungeonGenerator to achieve that. A brief description can be found [here](https://ondrejnepozitek.github.io/ProceduralLevelGenerator-Unity/docs/tilemapLayers).

By default, [this](https://github.com/OndrejNepozitek/ProceduralLevelGenerator-Unity/blob/master/Assets/ProceduralLevelGenerator/Scripts/GeneratorPipeline/RoomTemplates/TilemapLayers/TilemapLayersHandler.cs) TilemapLayersHandler is used. I would suggest to copy the source of this class and simply remove the code that adds RigidBody and CompositeCollider. Then create an instance of the ScriptableObject and assign it to the PayloadInitializer.

**Comment by muafakul** [comment]
extremely super cool ,thanks :D

**Comment by muafakul** [comment]
i just want to make sure ,, we can not use this or there is some way to add this ?

![image](https://user-images.githubusercontent.com/13078369/71064552-f14c9280-21a1-11ea-9431-0b16636a17b1.png)


because i want to add start and finish feature ,,i mean ,, auto add spawn point when i generate the map

**Comment by OndrejNepozitek** [comment]
I'havent used the GameObject Brush yet, so unfortunately I don't know how exactly that works and whether it can be used in the plugin.  But I think that you should be able to use a solution that I prepared for another user of the plugin. The idea is that you can add GameObjects to RoomTemplates and they are then instantiated after the level is generated.

Follow the description of how to do that:

>  "I created a simple pipeline task that will spawn game objects for you. You can find it here - https://gist.github.com/OndrejNepozitek/0316e90ebea833bd55576762c49ad4de
> 
> Usage:
> 1) Create instance of the task - Right click -> Create -> Dungeon generator -> Custom Tasks -> Spawn GameObjects
> 2) Add the task to the generator pipeline (see https://ondrejnepozitek.github.io/ProceduralLevelGenerator-Unity/docs/generatorSetup) after the generator itself
> 3) Open your room template and inside it create an empty "GameObjects" GameObject (the name is important - the task needs it to work)
> 4) Add GameObjects you would like to spawn as children of the "GameObjects"
> 5) Now after you generate your level, the pipeline task will go through all the spawned rooms, look for  "GameObjects" GameObject and then instantiate all its children (and correct their positions)"

So you would add your "Start" and "Finish" game objects to the corresponding room templates and the pipeline task should spawn them after your level is generated.

I want to include this functionality in the future releases of the plugin itself.

**Comment by muafakul** [comment]
thanks a lot 🍡

**Comment by muafakul** [comment]
extremely cool ,it works :D
