### ISSUE TITLE
The name 'AssetDatabase' does not exist in the current context

### ISSUE THREAD

**Issue by muafakul** [OndrejNepozitek/ProceduralLevelGenerator-Unity#32]
![image](https://user-images.githubusercontent.com/13078369/70856010-db6f7100-1f06-11ea-83ef-c9449f8eed5a.png)

**Comment by OndrejNepozitek** [comment]
Hey, thanks for your feedack!
It should be fixed in the latest release. Can you verify that everything works now as expected?

**Comment by muafakul** [comment]
i fixe it bya ading if end statement
