### ISSUE TITLE
Epic Fail if i use for Unity 2017 

### ISSUE THREAD

**Issue by muafakul** [OndrejNepozitek/ProceduralLevelGenerator-Unity#34]
![image](https://user-images.githubusercontent.com/13078369/71094129-009d0180-21dd-11ea-8ff3-f6aac8c738b8.png)

when i import using unity 2017 project ,it fail ,, so this project only of 2019 ?

**Comment by OndrejNepozitek** [comment]
It should work in Unity 2018.3 and newer because it uses C# 7 features.

**Comment by muafakul** [comment]
ah ok cool
