### ISSUE TITLE
Can you please explain adding enemies to documentation?

### ISSUE THREAD

**Issue by farazk86** [OndrejNepozitek/ProceduralLevelGenerator-Unity#39]
Hi,

Ive been trying to make this run on a tileset that I bought and I'm a bit stuck. The tilemap is similar to Example2 as there is a thin layer above the walls. Can I use the same corridor correction file for my tileset that you used for Example 2, or will I have to write my own?

And from reading the comments on your blog, I understand that enemies can also be automaticaly spawned as part of the generation pipeline. But there is no mention of it in the documentation.

Can you please explain how that would be possible?

Thank you

**Comment by OndrejNepozitek** [comment]
Hey!
regarding the tilemap, it depends how similar the two tilesets are. You can try to use the correction file from Example 2 and if it doesn't work, try to write your own. To be more precise, you can use the correction task from Example 2 and provide your own correction layout as can be seen here https://ondrejnepozitek.github.io/ProceduralLevelGenerator-Unity/docs/corridorsCorrection.

Regarding the spawn of enemies:
>  "I created a simple pipeline task that will spawn game objects for you. You can find it here - https://gist.github.com/OndrejNepozitek/0316e90ebea833bd55576762c49ad4de
> 
> Usage:
> 1) Create instance of the task - Right click -> Create -> Dungeon generator -> Custom Tasks -> Spawn GameObjects
> 2) Add the task to the generator pipeline (see https://ondrejnepozitek.github.io/ProceduralLevelGenerator-Unity/docs/generatorSetup) after the generator itself
> 3) Open your room template and inside it create an empty "GameObjects" GameObject (the name is important - the task needs it to work)
> 4) Add GameObjects you would like to spawn as children of the "GameObjects"
> 5) Now after you generate your level, the pipeline task will go through all the spawned rooms, look for  "GameObjects" GameObject and then instantiate all its children (and correct their positions)"

So you would add your enemies as a child of "GameObject" in each room template and the task will instantiate them at the correct location.

I know that the way you have to correct corridors and spawn gameobject/enemies is far from ideal. **I'm currently finishing an alpha version of this plugin that contains major changes in how are things done, trying to make everything simpler for the user.** Example 2 will no longer need to have a door correction task and gameobjects inside room templates will be handled automatically by the plugin.

**Comment by farazk86** [comment]
Thanks for replying. I'll give this a shot and let you know how I get along.

Would it be possible to give a time frame as to when can we expect the next version of your plugin?

Thanks

**Comment by OndrejNepozitek** [comment]
I would like to have the first alpha version available by the end of the week.

**Comment by farazk86** [comment]
Thats very good news. Thanks. 

I believe in that case it would not be wise to use this now. I'll just wait for the alpha version and work on other aspects of my game till then :)

**Comment by farazk86** [comment]
Many thanks for the update - I'm excited to try it out. :)

Excellent idea with the pro version as your asset can do more in 2D than most available on the asset store. 

Please link it here as well when its available on the asset store

**Comment by OndrejNepozitek** [comment]
I hope you'll like it. I'll let you when it's ready.

Also please let me know if you have any problems or questions about the plugin and I'll try to solve that as soon as possible,

**Comment by OndrejNepozitek** [comment]
> Ive been trying to make this run on a tileset that I bought and I'm a bit stuck. The tilemap is similar to Example2 as there is a thin layer above the walls. Can I use the same corridor correction file for my tileset that you used for Example 2, or will I have to write my own?

You can now use the [*outline override*](https://ondrejnepozitek.github.io/ProceduralLevelGenerator-Unity/docs/examples/example-2#vertical-corridors) feature for tilesets similar to [Example 2 in the documentation](https://ondrejnepozitek.github.io/ProceduralLevelGenerator-Unity/docs/examples/example-2).

Let me know if your tileset cannot be handled with this.
