### ISSUE TITLE
Level Graph grid Snapping

### ISSUE THREAD

**Issue by TechieCrow** [OndrejNepozitek/ProceduralLevelGenerator-Unity#43]
Snapping the room nodes to the grid so we can have a little nicer placement would be amazing but I guess it's a little pet peeve of mine haha. :)

**Comment by OndrejNepozitek** [comment]
Hey, thanks for you suggestion! That should be quite easy to implement, might look into that later.

**Comment by TechieCrow** [comment]
Awesome thank you! I discovered this today and have been figuring everything out, it's honestly the best generator I've found for 2D dungeons and plan on using it for my project so hopefully I can help find any bugs. :)

**Comment by OndrejNepozitek** [comment]
Thanks! Don't hesitate to let me know if you have any questions or problems.

**Comment by TechieCrow** [comment]
I have just tried the latest update and the snap to grid seems to be working perfect! I also love you added a zoom too! <3

**Comment by OndrejNepozitek** [comment]
I'm glad you like it!
