### ISSUE TITLE
Changing the random seed value last minute

### ISSUE THREAD

**Issue by TechieCrow** [OndrejNepozitek/ProceduralLevelGenerator-Unity#44]
Sorry to bother I was just hoping to get your input on this.

I am currently trying to change the dungeon seed value right before it generates the dungeon, my project is a multiplayer game so my ultimate plan is to have the server generate a random dungeon and when clients connect it will tell the clients what seed to use, to make things easier on me I'm hoping to leave the "Use Random Seed" open on but change the seed right before the generator uses it so all clients generate the same dungeon.

I'm not against disabling the "Use Random Seed"  open for clients joining a server but it would be easier for me to leave it on.

 Any ideas? :)

**Comment by OndrejNepozitek** [comment]
All the values that you see in the Editor when configuring the generator can be changed from a script. If you have an instance of the generator, you can set `generator.OtherConfig.UseRandomSeed` to false and `generator.OtherConfig.RandomGeneratorSeed` to any seed that you want. Unfornutately, this is not yet covered in the documentation as the structure of these configs is relatively new and I'm not yet sure if I'm happy with its current state.

I don't know how you use the generator, but if you manually obtain the DungeonGenerator component and then call the Generate() method (which is how I do it in the example scenes, its located e.g. in Example1GameManager), I'd change the seed right before calling Generate(). And if you use the "GenerateOnStart" option to generate the dungeon when the scene is loaded, you can quite easily convert that to the manual approach.

Is that what you need?

**Comment by TechieCrow** [comment]
Thanks! that's help a lot and managed to get it working! Here is how I managed it in case anyone stumbles on this issue. :D 

```c#
    public DungeonGenerator dg;
    public int ranseed;

    // Get the message ready
    public class SeedMsg : MessageBase
    {
        public int seed;
    }

    // When server starts, generate a random seed and a dungeon based on that seed
    public override void OnStartServer()
    {
        ranseed = Random.Range(0, 9999999);
        dg.OtherConfig.RandomGeneratorSeed = ranseed;
        dg.Generate();
    }

    // When a player joins, send the seed message
    public override void OnServerAddPlayer(NetworkConnection conn)
    {
        conn.Send(new SeedMsg { seed = ranseed });
        base.OnServerAddPlayer(conn);
    }

    // When the client starts register the seed message
    public override void OnStartClient()
    {
        NetworkClient.RegisterHandler<SeedMsg>(OnSeedMsg);
    }

    // After receving the seed message, generate the same dungeon as the server
    void OnSeedMsg(NetworkConnection conn, SeedMsg msg)
    {
        dg.OtherConfig.RandomGeneratorSeed = msg.seed;
        dg.Generate();
    }
```

The reason I have the DungeonGenerator stuff twice is once for the server and again for the client, the server needs to generate before the client as I have ```NetworkStartPosition``` stuff in the starting room prefab so the players always start in the correct room, I'm sure there is a better way of doing this and I will be fixing it up later but it works so I'm happy for now lol.

**Comment by OndrejNepozitek** [comment]
Great! I'm closing the issue now.
