### ISSUE TITLE
Are there any ways to get size(or bounds) of the rooms? (or the room's doors position)

### ISSUE THREAD

**Issue by longtran2904** [OndrejNepozitek/ProceduralLevelGenerator-Unity#45]
I have a question: How to get the size of each generated rooms? In my game, i want to know the which rooms the player's at so the way to do it is just take the room position and the size of the room and compare it to the player position. I know how to get the room position but what about the size? Or it will be easier if you can show me how to get the doors position?

**Comment by OndrejNepozitek** [comment]
I'm glad you like it. If you have any screenshots of your game to share (now or after you finish it) , I'd love to see how people use this plugin in their games.

**Comment by longtran2904** [comment]
A small question: In the list that GetOutlinePoints() return what is the order of the conner?

**Comment by OndrejNepozitek** [comment]
They should always be in the clockwise order. If you tell me what you're trying to accomplish I can maybe point you in the right direction.
