### ISSUE TITLE
How to close off dead end?

### ISSUE THREAD

**Issue by longtran2904** [OndrejNepozitek/ProceduralLevelGenerator-Unity#47]
I saw in the examples that your rooms was tight (all the outlines have tiles) and when the corridoors connect to it, it would disable the tile at the door's position. I didn't use corridor in my game (it was a 2d side scroller) so how could i achived this? While I testing by having tiles at door's position i noticed that if the room was generated first it would disable the tile at the connection, if not it wouldn't.

**Comment by OndrejNepozitek** [comment]
Can you please show me an example of a room template from your game?

**Comment by longtran2904** [comment]
This is before;
![image](https://user-images.githubusercontent.com/53656110/80279444-f0b3a200-8727-11ea-9830-5e766e3c994f.png)

This is after:
![image](https://user-images.githubusercontent.com/53656110/80279475-2193d700-8728-11ea-9e66-bb418beccff5.png)

I just want to close off dead end so i thought the generator would automated removed the tiles
P/S: The door's mode is specific and the position is at the 2 tiles up and below

**Comment by OndrejNepozitek** [comment]
If I understand your goal, I'd the the following. In your room templates, add wall tiles to all your door positions. And then create a special corridor room like in the image below. The width of the room is 4 tiles, the height is 2 tiles. Black are walls, red is one door position, pink is another door position (and there should be your purple background tiles under the doors).

![image](https://user-images.githubusercontent.com/2265359/80279728-b0d8c480-86ff-11ea-9c6d-a9bf1f8d7db4.png)

The only purpose of this corridor room is that it will correctly connect two adjacent rooms. So it is not really a corridor, but rather a connector. And by using this corridor, your dead ends will be handled automatically, because if there is not adjacent room, there will be no corridor and the room will look like in your 'after' picture.

If you need also a connector in the horizontal direction, just create another corridor room, this time width 2, height 4 and just rotate the design.

Then assign these corridor room templates to your level graph and enable corridor.

Let me know if that works for you.

**Comment by longtran2904** [comment]
It keep having this error: InvalidOperationException: Timeout was reached when generating level
The error is happened in: DungeonGeneratorPipelineConfig
And what layer should i draw the corridoor?
Here is the picture (i also made a horizontal one):
![image](https://user-images.githubusercontent.com/53656110/80280357-c8c73d00-872d-11ea-921f-79785381bdb7.png)

**Comment by OndrejNepozitek** [comment]
This is quite strange. Can you please check that if you disable corridors now, everything works as before? 

- How many rooms are there in the level graph?
- What is you "Timeout" configuration in the Generator component?

Also please check this:
- You added corridors to the "Corridor room templates" section in the level graph. The corridors cannot be in the "Default room templates" section.
![image](https://user-images.githubusercontent.com/2265359/80280736-38c1cd00-8706-11ea-8dd6-a59f587e8cba.png)
- You kept the same rooms in the level graph as before. The rooms in the level graph do not have to be modified to add corridors. Corridors are automatically added between each pair of adjacent rooms in the level graph.

**Comment by longtran2904** [comment]
0. If i disable corridors it still worked fine
1. I was testing so there were 6 rooms
2. 10000
3. I also did that
4. Yes, i don't change anything

**Comment by longtran2904** [comment]
Maybe because the layer that i drawing? Does the tilemap layers matter?

**Comment by longtran2904** [comment]
Here is the entire debug text:
InvalidOperationException: Timeout was reached when generating level
Assets.ProceduralLevelGenerator.Scripts.Generators.DungeonGenerator.PipelineTasks.DungeonGeneratorPipelineTask`1+<Process>d__0[TPayload].MoveNext () (at Assets/ProceduralLevelGenerator/Scripts/Generators/DungeonGenerator/PipelineTasks/DungeonGeneratorPipelineConfig.cs:72)
Assets.ProceduralLevelGenerator.Scripts.Pipeline.PipelineRunner+<GetEnumerator>d__1.MoveNext () (at Assets/ProceduralLevelGenerator/Scripts/Pipeline/PipelineRunner.cs:144)
Assets.ProceduralLevelGenerator.Scripts.Pipeline.PipelineRunner.Run (System.Collections.Generic.IEnumerable`1[T] pipelineItems, System.Object payload) (at Assets/ProceduralLevelGenerator/Scripts/Pipeline/PipelineRunner.cs:18)
Assets.ProceduralLevelGenerator.Scripts.Generators.DungeonGenerator.DungeonGenerator.Generate () (at Assets/ProceduralLevelGenerator/Scripts/Generators/DungeonGenerator/DungeonGenerator.cs:79)
Assets.ProceduralLevelGenerator.Scripts.Generators.DungeonGenerator.Editor.DungeonGeneratorInspector.OnInspectorGUI () (at Assets/ProceduralLevelGenerator/Scripts/Generators/DungeonGenerator/Editor/DungeonGeneratorInspector.cs:63)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass55_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <c10752821eec4acbb89ccd53fbbc5e27>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by OndrejNepozitek** [comment]
Can you please also show me how the second corridor looks like? Also if you're willing to just zip your Assets folder and send me the project, I can look into that myself.

The error itself is unfortunately useless. It just shows that the underlying algorithm is not able to generate a layout, which really should not happen with such a simple setup.

**Comment by OndrejNepozitek** [comment]
Oh, I just remembered that there should be a built-in export for the input of the algorithm. In the Generator component, there is an "Advanced" section with a "Export map description" button.  Please click the button and it should create a json file in the root of your project. If you send mi the file, I can try to find the problem.

**Comment by longtran2904** [comment]
![image](https://user-images.githubusercontent.com/53656110/80281259-1ba3f300-8734-11ea-8a93-fc184d771a2f.png)

**Comment by longtran2904** [comment]
Github doesn't support json so i send the txt
[exportedMapDescription.txt](https://github.com/OndrejNepozitek/ProceduralLevelGenerator-Unity/files/4533041/exportedMapDescription.txt)

**Comment by OndrejNepozitek** [comment]
Okay, thanks. I might know where's the problem. The doors mode of corridors must be "specific" and you must draw the door positions yourself. It seems like you used the simple mode with door length 1. And there was therefore a mismatch if door lenghts. I shoud have been more clear when describing the setup.

**Comment by longtran2904** [comment]
Yes that's fix the problem.
Thanks!
