### ISSUE TITLE
Tilemap didn't save the transform of a tile

### ISSUE THREAD

**Issue by longtran2904** [OndrejNepozitek/ProceduralLevelGenerator-Unity#49]
This is a problem that i've already knew in unity when i was trying to save and spawn an array of tiles. If you rotated or flipped the tile when drawing (by pressing "[" or "Shift+[") and then saved it back into an array it wouldn't save the transform of it so when you spawned the tiles back it would be flipped back to normal which was really weird. Some of my rooms while drawing i flipped and it wouldn't be stored. Are there any ways to get around it? I would recommend you to store the transform of the tiles (Matrix4x4) in the next update.

**Comment by OndrejNepozitek** [comment]
I've got a hotfix for you. I'll add this to the next version of the plugin but if you want it working now, do the following. Find the "PostProcessUtils.cs" file (Assets\ProceduralLevelGenerator\Runtime\Generators\Common\Utils) and find line 73. Below this line, add the following:
```
destinationTilemap.SetTransformMatrix(tilemapPosition + offset, sourceTilemap.GetTransformMatrix(tilemapPosition));
```

The result should look like this:
```
        public static void CopyTiles(List<Tilemap> sourceTilemaps, List<Tilemap> destinationTilemaps, Vector3Int offset)
        {
            sourceTilemaps = RoomTemplateUtils.GetTilemapsForCopying(sourceTilemaps);

            DeleteNonNullTiles(sourceTilemaps, destinationTilemaps, offset);

            foreach (var sourceTilemap in sourceTilemaps)
            {
                var destinationTilemap = destinationTilemaps.FirstOrDefault(x => x.name == sourceTilemap.name);

                if (destinationTilemap == null)
                {
                    continue;
                }

                foreach (var tilemapPosition in sourceTilemap.cellBounds.allPositionsWithin)
                {
                    var tile = sourceTilemap.GetTile(tilemapPosition);

                    if (tile != null)
                    {
                        destinationTilemap.SetTile(tilemapPosition + offset, tile);
                        destinationTilemap.SetTransformMatrix(tilemapPosition + offset, sourceTilemap.GetTransformMatrix(tilemapPosition));
                    }
                }
            }
        }
```

**Comment by longtran2904** [comment]
I added the code, but when i generated the level again it still didn't worked, the tile still reset it transform.

**Comment by longtran2904** [comment]
I was trying to debug it and when Debug.Log the sourceTilemap.GetTransformMatrix(tilemapPosition) it show: 
1.00000	0.00000	0.00000	0.00000
0.00000	1.00000	0.00000	0.00000
0.00000	0.00000	0.00000	0.00000
0.00000	0.00000	0.00000	1.00000
for all the tiles which was weired because i had some tiles that was flipped. Do i need to create a new room template or just use the old one.

**Comment by OndrejNepozitek** [comment]
You should be able to use your old room templates.  If I understand it correctly, Unity should save the transformation data when serializing the room template, right? Did you try restarting Unity?

What I did when I tried it:
- Add one rotated tile to a room template
- Generate level, the tile is not rotated
- Add the SetTransformMatrix line to the source code
- Generate level, the tile is correctly rotated

**Comment by longtran2904** [comment]
I thought Matrix4x4 wasn't serializable. I tested it by flipping, rotating it and it still not working. Your line of code was setting the transform from the sourceTilemap to the destinationTilemap but the transform of sourceTilemap (when i debug.log it) wasn't flipped or rotated which is the source of the problem (again i didn't think that Matrix4x4 was serializable and Unity wouldn't save it).

**Comment by longtran2904** [comment]
And i tried to restart Unity too.

**Comment by longtran2904** [comment]
I tried creating a new room template and rotated a tile. It still didn't work. Maybe because i was using the custom room template and tilemaphandler

**Comment by OndrejNepozitek** [comment]
Which version of Unity do you use? Maybe it's really a serialization issue
of Unity. I think it has nothing to do with your custom room template.

**Comment by longtran2904** [comment]
Unity 2019.3.1f1

**Comment by longtran2904** [comment]
Why don't you try to debug.log the the sorceTilemap's transform and see if it actually save at rotated and compare it to me? If true then there is most likely because the unity version and serialization issue.

**Comment by OndrejNepozitek** [comment]
I'm using Unity 2019.3.1f1, too.

So I tried to debug it. I rotated one single tile in a single room template by pressing "[" 3 times. When debugging, I see that there is once this:
```
0.00000	1.00000	0.00000	0.00000
-1.00000	0.00000	0.00000	0.00000
0.00000	0.00000	1.00000	0.00000
0.00000	0.00000	0.00000	1.00000
```
This seems correct because there is exactly one rotated tile in the whole level.

Now when I open the prefab file of the room template and look for the "-1", I see this:
```
  m_TileMatrixArray:
  - m_RefCount: 1
    m_Data:
      e00: 0
      e01: 1
      e02: 0
      e03: 0
      e10: -1
      e11: 0
      e12: 0
      e13: 0
      e20: 0
      e21: 0
      e22: 1
      e23: 0
      e30: 0
      e31: 0
      e32: 0
      e33: 1
```

Which looks like it's exactly the transformation matrix that I'm looking for. Maybe you can also look into that room template file and see what is there?

**Comment by longtran2904** [comment]
How to look into that? Is it from the json file of generated leve?

**Comment by OndrejNepozitek** [comment]
No. This is the room template prefab. Something like "Assets\ProceduralLevelGenerator\Examples\EnterTheGungeon\Room templates\Entrance.prefab". This is the one that I tried this on. It is just the native Unity serialization of the Room template game object.

**Comment by longtran2904** [comment]
I don't have the folder "EnterTheGungeon", just have "Example1", ... But i still tried it on "Room 1" in "Assets\Pro..\Examples\...Example1\Room templates\Room 1.prefab" and it didn't work.
Rotated tiles:
![image](https://user-images.githubusercontent.com/53656110/80373018-9f89e680-88be-11ea-834d-b5e70b8f505d.png)

When generated:
![image](https://user-images.githubusercontent.com/53656110/80373071-b597a700-88be-11ea-8092-51ae1d953aae.png)

**Comment by OndrejNepozitek** [comment]
One more thing to try: Add a rotated tile to the Room 1 room template, but use a tile from the Example 1 tile palette? Maybe there is a problem with your tiles/tile palette?

**Comment by longtran2904** [comment]
Still didn't work:
![image](https://user-images.githubusercontent.com/53656110/80373827-dad8e500-88bf-11ea-9c8d-2323bebecf80.png)

After:
![image](https://user-images.githubusercontent.com/53656110/80373871-edebb500-88bf-11ea-9ef6-cc9236afa2d4.png)

Does the example use a different script? Should i pass the line of code to somewhere in there?

**Comment by longtran2904** [comment]
Are there any other ways to get and set the transform of the tiles in your code?

**Comment by OndrejNepozitek** [comment]
This is really weird.

I also tried it in Unity 2018.4.18f1 and it works. I tried it with both Example 1 and Example 2 tile palettes.

This is the exact version of the PostProcessUtils files that I'm using - https://gist.github.com/OndrejNepozitek/9d489680f57549373684236c3247c309 . I added a debug.log with "Trying to correct the transformation" to really check that you use the correct version of the file.

**Comment by longtran2904** [comment]
The directory of your namespace is different than me.
Mine is Assets.ProceduralLevelGenerator.Scripts.Generators.Common.Rooms, and your is ProceduralLevelGenerator.Unity.Generators.Common.Rooms. Does it affect anything? Should i change it to mine?

**Comment by OndrejNepozitek** [comment]
This is from the newest version of the plugin so you can change it back to yours.

**Comment by OndrejNepozitek** [comment]
This is the "Assets\Pro..\Examples...Example1\Room templates\Room 1.prefab" file after I added several rotated tiles to it: https://gist.github.com/OndrejNepozitek/eb3686db8f96505f45d0637e38f27300 For example on line 2492 you can see a "-1" in the rotation matrix which hints that something is rotated/flipped. 

Can you try what happend if xou replace your "Assets\Pro..\Examples...Example1\Room templates\Room 1.prefab" with the content of the gist?

Steps:
- replace the content of the file
- open the Room 1 room template in unity, check that there are some rotated banners inside of the room
- generate a level and check if the banners are still rotated or not

**Comment by longtran2904** [comment]
Do that, all the banners reset their transform when generated.

**Comment by longtran2904** [comment]
Let's me try using this in another project i have

**Comment by longtran2904** [comment]
After created a new project (2019.3.1f1) and go into example 1 the problem still existed. Maybe you can try to create a new project on your own, then import your plugin and test it?

**Comment by OndrejNepozitek** [comment]
It seems that I was finally able to reproduce the issue in an older version of the plugin.

**Comment by longtran2904** [comment]
Which version? v2 or v1.x

**Comment by longtran2904** [comment]
Have you figured it out what is the problem yet?

**Comment by OndrejNepozitek** [comment]
Yeah, I was able to fix that.

If you use the v2.0.0-alpha.1-hotfix.1 or some slightly older version, there is one more change needed. In the file "Assets/ProceduralLevelGenerator/Scripts/Generators/Common/Utils/GeneratorUtils.cs" you need to commend the lines 43 and 44:

```
//var transformation = layoutRoom.Transformation;
//roomTransformations.Transform(roomTemplateInstance, transformation);
```

Or if you use the newest v2.0.0-alpha.2 version, only the change with the PostProcessUtils file is needed.

I'd probably recommend to update to the newest version but there are some breaking changes (you would have to remove all the old files of the plugin and then import the new files, so it would only work if you didn't change anything in the directory with the plugin. And after you import it, there may be some namespace problems which should be easily fixed by Visual Studio or a similar IDE. All the details are in the release page. And you should not lose any data like Room templates or settings, etc.

Thanks for your patience and that you help me improve the plugin!

**Comment by longtran2904** [comment]
Yes, it've finally been fixed. Thank you so much for helping me. I really appriciate it.

Wish you the best!
