### ISSUE TITLE
Changing specific room tags and layers

### ISSUE THREAD

**Issue by TechieCrow** [OndrejNepozitek/ProceduralLevelGenerator-Unity#55]
So my game would require "secret rooms", I'm wondering if it's currently possible to keep the tags and layers of specific rooms?

My idea is to have the rooms invisible to the player by culling the room layer on the camera then changing it to default when the player enters a trigger, normally this would work but the algorithm merges all rooms into one tilemap. Any ideas?

**Comment by longtran2904** [comment]
If you don't want to merges all rooms into one tilemap just disable all the tilemap-related checkbox in the post processing config of the dungeon generator. If you want to make a custom room template which has a predefined layers, gameobject,... you can look at it here: https://github.com/OndrejNepozitek/ProceduralLevelGenerator-Unity/issues/48

**Comment by OndrejNepozitek** [comment]
As longtran2904 said, you can configure the algorithm to not merge all the rooms to a single tilemap. However, this comes with a price. If you don't merge them, all the wall colliders of individual room will still be in place so you won't be able to go from one room to another. So you would have to add some postprocessing to let players go from one room to another. This is one of the main reasons for merging the rooms - you don't have to handle these colliders which is I think better for new user.

I'm open to suggestions on how to handle this better.

When I experimented with revealing and hiding rooms, I wrote a post processing shader that would translate pixels on screen to world coordinates and hide rooms that were not yet revealed.

**Comment by TechieCrow** [comment]
Cool thanks for the advice guys, luckily for me as it's only for rare secret rooms I can edit the tilemaps after the level is generated with minimal effort.

The way i'm hoping to hide and reveal rooms makes it much easier to work with multiplayer games.
