### ISSUE TITLE
Doors lenght

### ISSUE THREAD

**Issue by pvalium** [OndrejNepozitek/ProceduralLevelGenerator-Unity#58]
Hi!.
I don't know how can I put a door of a lenght=2. I've tried to use corridors of size 2 tiles, and visually all is ok, the corridor intersects with room and the entry is 2 tiles length, but when I look the doorEntity  of the RoomInstance, always says that lenght is 1, and From is equal to To.

My config
Room has size doors = 2
Corridor has 2 tiles for walls, 2 tiles for floor, with 2 doors in each edge. I think maybe this is the problem, but I don't know if is possible put a door of size 2x1 in a corridor.

All this stuff is because I want to instance door prefab, but I need the correct lenght.

Any ideas

**Comment by OndrejNepozitek** [comment]
Hey! 

1. Can you please show me a screenshot of how your corridor and its door positions look?
2. There is an "Advanced" section in the Dungeon Generator component and there should be an "Export map description" button. Click the button and it should create a file called "exportedMapDescription.json" in the root folder of your project. Please send me this file - it contains information about the shapes of your rooms.

**Comment by pvalium** [comment]
Ok, My mistake!. I've discovered that you can drag mouse when you put doors manually, increasing the size

Sorry and thanks! 

PD: Your work are awesome.

**Comment by OndrejNepozitek** [comment]
I'm glad you like it!
