### ISSUE TITLE
Custom room on LevelGraph

### ISSUE THREAD

**Issue by geuks** [OndrejNepozitek/ProceduralLevelGenerator-Unity#63]
Hi, i'm trying to do the same as your Enter The Dungeon exemple wich is adding a custom room in Level Graph. 

![Capture](https://user-images.githubusercontent.com/23451354/82275838-ff3a5580-9983-11ea-98c0-b37f9e69b617.PNG)

How do you do that ? I tried to create my own custom Level Graph but it didn't work as i want to.
Can you help me ? thanks. (I have pro version)

**Comment by OndrejNepozitek** [comment]
Hey! This is currently on my list of features that need to be documented.

You have to create a class that implements from the Room class. In the Enter the Gungeon example, it is done like this:

    public class GungeonRoom : Room
    {
        public GungeonRoomType Type;

        public override string ToString()
        {
            return Type.ToString();
        }
    }

After that, when you create a level graph and select it in the inspector, you should be able to choose which room type should be used for the graph. And there you have to choose your new room implementation from the dropdown.

![image](https://user-images.githubusercontent.com/2265359/82291821-fd838880-99a9-11ea-80bf-f8d02c81db8d.png)

However, it seems like there was some merge problem which made it impossible to choose a different room type than the default type. This should be now fixed and a new version was added to itch.io

P.S. You should be able to add various additional fields to your custom room, not just the type. It should work as long as Unity is able to serialize it.

**Comment by geuks** [comment]
Thanks, it works now !
